# Generated by Django 5.0.2 on 2025-12-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplan_api', '0004_materia_periodoacademico_aula_grupo_solicitudcambio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('BAJA', 'Baja')], default='ACTIVA', max_length=10)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.RenameIndex(
            model_name='horario',
            new_name='eduplan_api_aula_id_664ab9_idx',
            old_name='sistema_bua_aula_id_d20ded_idx',
        ),
        migrations.RenameIndex(
            model_name='horario',
            new_name='eduplan_api_docente_9bb26a_idx',
            old_name='sistema_bua_docente_8e266c_idx',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eduplan_api.alumnos'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eduplan_api.grupo'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='eduplan_api.periodoacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'grupo', 'periodo')},
        ),
    ]
