# Generated by Django 5.0.2 on 2025-12-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplan_api', '0005_inscripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcambio',
            name='fecha_propuesta',
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='dia_semana_propuesto',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')], help_text='Día de la semana propuesto para el nuevo horario', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='hora_fin_propuesta',
            field=models.TimeField(blank=True, help_text='Hora de fin propuesta para el nuevo horario', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='hora_inicio_propuesta',
            field=models.TimeField(blank=True, help_text='Hora de inicio propuesta para el nuevo horario', null=True),
        ),
    ]
