# Generated by Django 5.0.2 on 2025-12-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplan_api', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambio',
            name='dia_semana_original',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')], default=0, help_text='Día de la semana que se desea cambiar'),
        ),
    ]
