# Generated by Django 5.0.2 on 2026-05-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplan_api', '0008_solicitudcambio_dia_semana_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
