# Generated by Django 5.0.2 on 2025-11-24 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('area_academica', models.CharField(max_length=150)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=10)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Periodo académico',
                'verbose_name_plural': 'Periodos académicos',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('edificio', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('recursos', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', max_length=15)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'unique_together': {('edificio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('semestre', models.PositiveSmallIntegerField()),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='sistema_buap_api.materia')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_propuesta', models.DateField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='sistema_buap_api.maestros')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='sistema_buap_api.grupo')),
            ],
            options={
                'verbose_name': 'Solicitud de cambio',
                'verbose_name_plural': 'Solicitudes de cambio',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=10)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='sistema_buap_api.aula')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='sistema_buap_api.maestros')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='sistema_buap_api.grupo')),
                ('periodo', models.ForeignKey(help_text='Periodo académico al que pertenece el horario', on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='sistema_buap_api.periodoacademico')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'indexes': [models.Index(fields=['aula', 'dia_semana', 'hora_inicio', 'hora_fin'], name='sistema_bua_aula_id_d20ded_idx'), models.Index(fields=['docente', 'dia_semana', 'hora_inicio', 'hora_fin'], name='sistema_bua_docente_8e266c_idx')],
            },
        ),
    ]
